### ISSUE TITLE
Link to github on the Google Web Store is 404

### ISSUE THREAD

**Issue by Zambonilli** [westoque/cookie_inspector#11]
Awesome, work on this extension.  I've been using it as better documentation on how to build a devtools extension than the official Google docs.  FYI, the link to this github project from the Google Web Store is a 404.

Google Web Store
https://github.com/westoque/cookie_inspect

Github project page
https://github.com/westoque/cookie_inspector

**Comment by westoque** [comment]
@Zambonilli Thanks a lot. I really appreciate the feedback. :+1:
