### ISSUE TITLE
Not render in selected color scheme

### ISSUE THREAD

**Issue by daniellz** [westoque/cookie_inspector#13]
I have dark theme in DevTools. And Cookies tab don't behave styles of ui.
http://take.ms/aZ65J

http://take.ms/VxsgD - native Resources tab
Opera Dev 38.0.2190 (Chrome/50.0.2661.26)

**Comment by clarketm** [comment]
I submitted a [pull request](https://github.com/westoque/cookie_inspector/pull/15) with basic *css* rule-sets specifically designed for the devtools dark theme. [[repo]](https://github.com/clarketm/cookie_inspector).

![image](https://cloud.githubusercontent.com/assets/9957358/23142447/d898d388-f770-11e6-9500-38f081f2c114.png)

**Comment by westoque** [comment]
@clarketm thanks for the PR  from a year ago. closing issue.
